from importlib.metadata import version

from .callback import verify_callback
from .client import Platega
from .enums import (
    CallbackSubscriptionStatus,
    PaymentMethodInt,
    PaymentStatus,
    SubscriptionInterval,
    SubscriptionStatus,
)
from .exceptions import (
    ClientDecodeError,
    PlategaAPIError,
    PlategaBadRequestError,
    PlategaConflictError,
    PlategaError,
    PlategaForbiddenError,
    PlategaNetworkError,
    PlategaNotFoundError,
    PlategaRateLimitError,
    PlategaServerError,
    PlategaUnauthorizedError,
    PlategaUnprocessableEntityError,
    PlategaValidationError,
)
from .payout import PayoutClient
from .types import (
    BalanceItem,
    BalancesResponse,
    CallbackPayload,
    CancelSubscriptionResponse,
    CancelSupportedResponse,
    CancelTransactionResponse,
    CardPayoutRequest,
    CardPayoutResponse,
    ConversionItem,
    ConversionsResponse,
    CreateSubscriptionResponse,
    CreateTransactionRequest,
    CreateTransactionResponse,
    ExportUrlResponse,
    H2HQrResponse,
    PaymentDetails,
    PaymentLinkResponse,
    PlategaObject,
    RateResponse,
    SavedCard,
    SavedCardsResponse,
    SequenceResponse,
    Subscription,
    SubscriptionChargeCallback,
    SubscriptionListResponse,
    SubscriptionStatusCallback,
    TransactionExportItem,
    TransactionExportRequest,
    TransactionExportResponse,
    TransactionStatusResponse,
)

__version__ = version("aioplatega")
"""Version of the installed distribution, declared in ``pyproject.toml``.

Read from the installed metadata rather than duplicated in a module, so that
``uv version --bump`` has a single place to change.
"""

__all__ = [
    "__version__",
    "BalanceItem",
    "BalancesResponse",
    "CallbackPayload",
    "CallbackSubscriptionStatus",
    "CancelSubscriptionResponse",
    "CancelSupportedResponse",
    "CancelTransactionResponse",
    "CardPayoutRequest",
    "CardPayoutResponse",
    "ClientDecodeError",
    "ConversionItem",
    "ConversionsResponse",
    "CreateSubscriptionResponse",
    "CreateTransactionRequest",
    "CreateTransactionResponse",
    "ExportUrlResponse",
    "H2HQrResponse",
    "PaymentDetails",
    "PaymentLinkResponse",
    "PaymentMethodInt",
    "PaymentStatus",
    "PayoutClient",
    "Platega",
    "PlategaAPIError",
    "PlategaBadRequestError",
    "PlategaConflictError",
    "PlategaError",
    "PlategaForbiddenError",
    "SequenceResponse",
    "PlategaNetworkError",
    "PlategaNotFoundError",
    "PlategaObject",
    "PlategaRateLimitError",
    "PlategaServerError",
    "PlategaUnauthorizedError",
    "PlategaUnprocessableEntityError",
    "PlategaValidationError",
    "RateResponse",
    "SavedCard",
    "SavedCardsResponse",
    "Subscription",
    "SubscriptionChargeCallback",
    "SubscriptionInterval",
    "SubscriptionListResponse",
    "SubscriptionStatus",
    "SubscriptionStatusCallback",
    "TransactionExportItem",
    "TransactionExportRequest",
    "TransactionExportResponse",
    "TransactionStatusResponse",
    "verify_callback",
]
